# Use an official Python runtime as the base image
FROM ubuntu:22.10
USER root

WORKDIR /usr/ecomm_comp

COPY ./ecomm_comp /ecomm_comp
COPY ./crontab /etc/cron.d/crontab
COPY requirements.txt /requirements.txt

# Install the required packages
RUN apt-get update && \
    apt-get install -y python3 python3-pip nano cron && \
    chmod a+x ./ecomm_comp/price_gathering_main.py && \
    python3 -m pip install --upgrade pip && \
    apt-get clean && \
    pip install --no-cache-dir -r requirements.txt && \
    crontab /etc/cron.d/crontab && \
    touch /tmp/out.log

# Define the command to run the app when the container launches
CMD ["python3", "temp2_opt.py"]